common: &common
  weibo:
    api_key: "2381201314"
    api_secret: "71b366aa0accc07ce719b47dcf7fd77b"
    redirect_uri: "http://localhost:3000/users/auth/weibo"
   # redirect_uri: "http://www.yourdomain.com/users/auth/weibo/callback"
    #https://api.weibo.com/oauth2/authorize?client_id=YOUR_CLIENT_ID&response_type=code&redirect_uri=YOUR_REGISTERED_REDIRECT_URI

production:
  <<: *common

development:
  <<: *common

test:
  <<: *common
